name: Generate deployments, copy to docs

on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: housekeeping-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Contracts repository
        uses: actions/checkout@v4
        with:
          ref: main
          path: contracts

      - name: Checkout Docs repository
        uses: actions/checkout@v4
        with:
          repository: whetstoneresearch/doppler-docs
          token: ${{ secrets.PAT_DOCS }}
          path: docs

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Generate deployment docs
        working-directory: ./contracts
        run: bun deployments/cli.ts --output=history

      - name: Commit and push generated files to contracts repository
        run: |
          cd contracts
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add Deployments.md Deployments.json deployments/*.md
          if [[ -n $(git status -s) ]]; then
            git commit -m "Update deployment docs - ${{ github.sha }}"
            git push
          else
            echo "No changes to commit to contracts repo"
          fi

      - name: Copy deployments file from contracts to docs
        run: |
          cp contracts/Deployments.md docs/resources/contract-addresses.md

      - name: Commit and push to the docs repository
        run: |
          cd docs
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # Check if there are changes
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Update deployments - ${{ github.sha }}"
            git push
          else
            echo "No changes to commit"
          fi
